#!/usr/bin/env python3
"""Fork hook inventory.

Every AyuGram and AiraGram feature reaches upstream code through a small
number of call sites planted in files Telegram owns. A `git merge` of a new
upstream release resolves those files textually; when upstream rewrote the surrounding function,
the merge can drop a hook and still produce a file that compiles, because the
hook's *definition* (in a fork-owned file) is untouched. The compiler flags a
missing definition; nothing flags a missing call.

This tool records every AYG/AIR symbol referenced from an upstream-owned file and
compares a later tree against that record.

    fork_hooks.py snapshot            # write tools/ayg-upstream/hooks.json
    fork_hooks.py check               # compare the tree against hooks.json
    fork_hooks.py check --against REF # compare two git revisions instead

`check` exits non-zero when a hook disappeared.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from collections import defaultdict

ROOT = subprocess.run(
    ["git", "rev-parse", "--show-toplevel"],
    capture_output=True, text=True, check=True,
).stdout.strip()

INVENTORY = os.path.join(ROOT, "tools", "ayg-upstream", "hooks.json")

SOURCE_SUFFIXES = (".swift", ".m", ".mm", ".h", ".c", ".cpp")

# A fork-owned file is ours end to end: upstream will never touch it, so a
# reference from one of these is not a hook, it is internal fork code.
FORK_OWNED_DIRS = ("submodules/AyuGramUI/", "submodules/AiraGramUI/")
FORK_OWNED_PREFIXES = ("AYG", "AIR")
FORK_OWNED_SEGMENT = re.compile(r"(^|/)(?:AYG|AIR)[A-Za-z0-9_]*(/|$)")

# `AYGFoo`/`AIRFoo` types and `aygBar`/`airBar` functions and properties.
#
# The `air` form requires a capital letter after the prefix, unlike `ayg`:
# upstream really does contain `airpods`, `airbnb`, `airplane` and friends, and
# nothing starting with `ayg`. `airagram` is then listed explicitly, because
# the enum case and the icon property that name the section are all-lowercase
# and are as load-bearing as any other hook — lose them and the Settings row
# disappears.
SYMBOL = re.compile(
    r"\b(?:AYG[A-Za-z0-9_]+|ayg[A-Za-z0-9_]+|AIR[A-Za-z0-9_]+|air[A-Z][A-Za-z0-9_]*|airagram[A-Za-z0-9_]*)\b"
)


def is_ayg_owned(path: str) -> bool:
    if path.startswith(FORK_OWNED_DIRS):
        return True
    if os.path.basename(path).startswith(FORK_OWNED_PREFIXES):
        return True
    return bool(FORK_OWNED_SEGMENT.search(os.path.dirname(path)))


def tracked_sources(rev: str | None) -> list[str]:
    if rev:
        out = subprocess.run(
            ["git", "ls-tree", "-r", "--name-only", rev],
            capture_output=True, text=True, check=True, cwd=ROOT,
        ).stdout
    else:
        out = subprocess.run(
            ["git", "ls-files"],
            capture_output=True, text=True, check=True, cwd=ROOT,
        ).stdout
    return [p for p in out.splitlines()
            if p.endswith(SOURCE_SUFFIXES) and not is_ayg_owned(p)]


def read(path: str, rev: str | None) -> str:
    if rev:
        r = subprocess.run(["git", "show", f"{rev}:{path}"],
                           capture_output=True, text=True, cwd=ROOT)
        return r.stdout if r.returncode == 0 else ""
    try:
        with open(os.path.join(ROOT, path), encoding="utf-8", errors="replace") as f:
            return f.read()
    except OSError:
        return ""


def collect(rev: str | None) -> dict[str, dict[str, int]]:
    """path -> {symbol: number of references}, for upstream-owned files only."""
    inventory: dict[str, dict[str, int]] = {}
    for path in tracked_sources(rev):
        text = read(path, rev)
        if not any(marker in text for marker in ("AYG", "ayg", "AIR", "air")):
            continue
        counts: dict[str, int] = defaultdict(int)
        for m in SYMBOL.finditer(text):
            counts[m.group(0)] += 1
        if counts:
            inventory[path] = dict(sorted(counts.items()))
    return dict(sorted(inventory.items()))


def snapshot(args) -> int:
    inv = collect(args.rev)
    payload = {
        "_comment": "Generated by tools/ayg-upstream/fork_hooks.py. "
                    "Every AYG/AIR symbol referenced from a file Telegram owns. "
                    "Regenerate deliberately, never to silence `check`.",
        "files": inv,
    }
    with open(INVENTORY, "w", encoding="utf-8", newline="\n") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
        f.write("\n")
    total = sum(sum(c.values()) for c in inv.values())
    print(f"wrote {os.path.relpath(INVENTORY, ROOT)}: "
          f"{len(inv)} upstream-owned files, {total} hook references")
    return 0


def check(args) -> int:
    if args.against:
        before = collect(args.against)
        label = args.against
    else:
        with open(INVENTORY, encoding="utf-8") as f:
            before = json.load(f)["files"]
        label = os.path.relpath(INVENTORY, ROOT)
    after = collect(args.rev)

    lost_files, weakened, new_files, new_symbols = [], [], [], []

    for path, symbols in before.items():
        if path not in after:
            lost_files.append((path, symbols))
            continue
        for sym, count in symbols.items():
            now = after[path].get(sym, 0)
            if now < count:
                weakened.append((path, sym, count, now))

    for path, symbols in after.items():
        if path not in before:
            new_files.append(path)
        else:
            for sym, count in symbols.items():
                if sym not in before[path]:
                    new_symbols.append((path, sym, count))

    print(f"Fork hook inventory: comparing working tree against {label}\n")

    if lost_files:
        print(f"LOST — {len(lost_files)} upstream-owned file(s) no longer reference the fork:")
        for path, symbols in lost_files:
            exists = os.path.exists(os.path.join(ROOT, path))
            why = "file gone (upstream deleted or renamed it)" if not exists else "hooks stripped"
            print(f"  {path}  [{why}]")
            for sym, count in symbols.items():
                print(f"      was: {sym} x{count}")
        print()

    if weakened:
        print(f"WEAKENED — {len(weakened)} hook(s) lost call sites:")
        for path, sym, was, now in weakened:
            print(f"  {path}: {sym}  {was} -> {now}")
        print()

    if new_files or new_symbols:
        print("ADDED (informational — re-run `snapshot` once reviewed):")
        for path in new_files:
            print(f"  + {path}")
        for path, sym, count in new_symbols:
            print(f"  + {path}: {sym} x{count}")
        print()

    if lost_files or weakened:
        print("A hook vanished. The build may still succeed and the feature will be dead.")
        print("Restore each call site, then re-run `snapshot`.")
        return 1

    print("OK — every recorded hook is still planted.")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("snapshot", help="record the current hook inventory")
    s.add_argument("--rev", help="read from a git revision instead of the working tree")
    s.set_defaults(func=snapshot)

    c = sub.add_parser("check", help="compare a tree against the recorded inventory")
    c.add_argument("--rev", help="read from a git revision instead of the working tree")
    c.add_argument("--against", help="compare against this revision instead of hooks.json")
    c.set_defaults(func=check)

    args = p.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
